fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: App\Entity\User
    group:
        group_class: App\Entity\Group
    from_email:
        address: "demo@example.com"
        sender_name: "AdminLTE Demo"
    registration:
        confirmation:
            enabled: false
            template: '@FOSUser/Registration/email.txt.twig'
    resetting:
        retry_ttl: 7200
        token_ttl: 86400
        email:
            template: '@FOSUser/Resetting/email.txt.twig'
        form:
            type: FOS\UserBundle\Form\Type\ResettingFormType
            name: fos_user_resetting_form
            validation_groups: [ResetPassword, Default]
    service:
        mailer: fos_user.mailer.twig_swift
