gest:
  # --------------------------------------------------------------------------------
  # PERMISSIONS
  # --------------------------------------------------------------------------------
  permissions:
    # mapping complex rule sets of single permissions to named "sets" ("set name" = [array of "permissions and sets"])
    sets:
      PROJECTS: ['view_project','create_project','edit_project','delete_project','permissions_project','comments_project','details_project']
      PROJECT_STEP: ['view_step','create_step','edit_step','delete_step','permissions_step','comments_step','details_step','assign_step']
      CUSTOMERS: ['view_customer','create_customer','edit_customer','delete_customer','permissions_customer','comments_customer','details_customer']
      CUSTOMERS_OWN: ['view_customeruser','edit_customeruser','permissions_customeruser','comments_customeruser','details_customeruser']
      CUSTOMERS_ALL_TEAM: ['view_team_customer','edit_team_customer','comments_team_customer','details_team_customer']
      CUSTOMERS_TEAMLEAD: ['view_teamlead_customer','edit_teamlead_customer','comments_teamlead_customer','details_teamlead_customer']
      USER: ['view_user','create_user','delete_user','role_permissions']
      EMPLOYEE: ['view_employee','create_employee','delete_employee','role_permissions']
        # some single default definitions for roles
      SINGLE_USER: ['view_step','edit_step','view_project']
      # link above sets to one complete set for each user role
      ROLE_USER: ['@SINGLE_USER']
      ROLE_TEAMLEAD: ['ROLE_TEAMLEAD']
      ROLE_CUSTOMER: ['ROLE_CUSTOMER','@USER','@PROJECTS','@PROJECT_STEP','@ROLE_USER','@CUSTOMERS_OWN']
      ROLE_COACH: ['ROLE_COACH']
      ROLE_ADMIN: ['ROLE_ADMIN','@USER']
      ROLE_SUPER_ADMIN: ['ROLE_SUPER_ADMIN','@EMPLOYEE','@PROJECTS','@PROJECT_STEP','@CUSTOMERS','@CUSTOMERS_ALL_TEAM','@CUSTOMERS_TEAMLEAD']
        # mapping "sets" or permissions to user roles ("role name" = [array of "set names"])
    maps:
      ROLE_USER: ['ROLE_USER']
      ROLE_TEAMLEAD: ['ROLE_TEAMLEAD']
      ROLE_CUSTOMER: ['ROLE_CUSTOMER']
      ROLE_COACH: ['ROLE_COACH']
      ROLE_ADMIN: ['ROLE_ADMIN']
      ROLE_SUPER_ADMIN: ['ROLE_SUPER_ADMIN']
      # only here to register the (partially) unused permissions in the UI
     # ROLE_FAKE: []
      # add or remove single permissions
    roles:
      ROLE_USER: []
      ROLE_TEAMLEAD: []
      ROLE_CUSTOMER: []
      ROLE_COACH: []
      ROLE_ADMIN: []
      ROLE_SUPER_ADMIN: []
   # --------------------------------------------------------------------------------

  # --------------------------------------------------------------------------------
  # LANGUAGES
  # Locale specific settings, like date formats
  # --------------------------------------------------------------------------------
  languages:
    cs:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m H:i'
    da:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    de:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    de_CH:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    en:
      date_time_type: 'yyyy-MM-dd HH:mm'
      date_type: 'yyyy-MM-dd'
      date: 'Y-m-d'
      date_time: 'm-d H:i'
      duration: '%%h:%%m h'
    es:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    eu:
      date_time_type: 'yyyy-MM-dd HH:mm'
      date_type: 'yyyy-MM-dd'
      date: 'Y-m-d'
      date_time: 'm-d H:i'
      duration: '%%h:%%m h'
    fr:
      date_time_type: 'dd/MM/yyyy HH:mm'
      date_type: 'dd/MM/yyyy'
      date: 'd/m/Y'
      date_time: 'd/m H:i'
      duration: '%%h h %%m'
    hu:
      date_time_type: 'yyyy.MM.dd. HH:mm'
      date_type: 'yyyy.MM.dd.'
      date: 'Y.m.d.'
      date_time: 'm.d. H:i'
    it:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    nl:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
      duration: '%%hu%%m'
    pt_BR:
      date_time_type: 'dd-MM-yyyy HH:mm'
      date_type: 'dd-MM-yyyy'
      date: 'd-m-Y'
      date_time: 'd-m H:i'
    ru:
      date_time_type: 'dd.MM.yyyy HH:mm'
      date_type: 'dd.MM.yyyy'
      date: 'd.m.Y'
      date_time: 'd.m. H:i'
    sk:
      date_time_type: 'dd. MM. yyyy HH:mm'
      date_type: 'dd. MM. yyyy'
      date: 'd. m. Y'
      date_time: 'd. m.  H:i'
    sv:
      duration: '%%h:%%m tim'
  # --------------------------------------------------------------------------------

